###############################################################################
# AWS Secrets Manager
#
# Passwords are generated by Terraform and written straight into Secrets
# Manager. They are never placed in tfvars and never appear in plan output.
#
# NOTE: generated values still land in Terraform state - keep state in an
# encrypted, access-controlled S3 bucket (see backend.tf).
###############################################################################

resource "random_password" "db" {
  length  = var.generated_password_length
  special = true
  # RDS master passwords cannot contain / @ " or spaces.
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "random_password" "keycloak_admin" {
  length           = var.generated_password_length
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

# random_id keeps secret names unique so a destroy/recreate cycle does not
# collide with a secret still inside its recovery window.
resource "random_id" "secret_suffix" {
  byte_length = 3
}

# ----------------------------------------------------------------------------
# Database credentials
# ----------------------------------------------------------------------------
resource "aws_secretsmanager_secret" "db" {
  name        = "${local.name_prefix}/rds/credentials-${random_id.secret_suffix.hex}"
  description = "Keycloak PostgreSQL master credentials for ${var.environment}"
  kms_key_id  = var.secrets_kms_key_arn

  recovery_window_in_days = var.secret_recovery_window_days


  tags = { Name = "${local.name_prefix}-rds-credentials" }
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id

  secret_string = jsonencode({
    engine   = "postgres"
    host     = aws_db_instance.keycloak.address
    port     = var.db_port
    dbname   = var.db_name
    username = var.db_username
    password = random_password.db.result
    jdbc_url = "jdbc:postgresql://${aws_db_instance.keycloak.address}:${var.db_port}/${var.db_name}"
  })
}

# ----------------------------------------------------------------------------
# Keycloak bootstrap admin credentials
# ----------------------------------------------------------------------------
resource "aws_secretsmanager_secret" "keycloak_admin" {
  name        = "${local.name_prefix}/keycloak/admin-${random_id.secret_suffix.hex}"
  description = "Keycloak bootstrap admin credentials for ${var.environment}"
  kms_key_id  = var.secrets_kms_key_arn

  recovery_window_in_days = var.secret_recovery_window_days


  tags = { Name = "${local.name_prefix}-keycloak-admin" }
}

resource "aws_secretsmanager_secret_version" "keycloak_admin" {
  secret_id = aws_secretsmanager_secret.keycloak_admin.id

  secret_string = jsonencode({
    username = var.keycloak_admin_username
    password = random_password.keycloak_admin.result
  })
}
