#!/bin/bash
# Provision a Samba AD domain (CORP.EXAMPLE.COM) on FIRST boot, create demo
# users + a group, then run the DC in the foreground. Subsequent boots reuse
# the domain database persisted in the /var/lib/samba volume.
set -euo pipefail

ADMIN_PASS="${AD_ADMIN_PASSWORD:-Adm1nP@ssw0rd!}"
STATE_DIR=/var/lib/samba

if [ ! -f "${STATE_DIR}/.provisioned" ]; then
    echo ">>> First boot: provisioning Active Directory domain CORP.EXAMPLE.COM ..."

    # Provision refuses to run if a default smb.conf exists
    rm -f /etc/samba/smb.conf

    samba-tool domain provision \
        --use-rfc2307 \
        --realm=CORP.EXAMPLE.COM \
        --domain=CORP \
        --server-role=dc \
        --dns-backend=SAMBA_INTERNAL \
        --adminpass="${ADMIN_PASS}"

    # Kerberos config generated by provisioning (handy for kinit tests)
    cp /var/lib/samba/private/krb5.conf /etc/krb5.conf || true

    echo ">>> Creating demo users and group (samba-tool works offline on the local DB) ..."
    # NOTE: --mail-address populates the AD 'mail' attribute — the attribute
    # Keycloak maps to the OIDC 'email' claim that NiFi identifies users by.
    samba-tool user create bob 'Password1!' \
        --given-name=Bob --surname=Builder \
        --mail-address=bob@corp.example.com
    samba-tool user setexpiry bob --noexpiry

    samba-tool user create carol 'Password1!' \
        --given-name=Carol --surname=Chen \
        --mail-address=carol@corp.example.com
    samba-tool user setexpiry carol --noexpiry

    samba-tool group add nifi-admins
    samba-tool group addmembers nifi-admins bob

    # /etc is NOT on the volume — keep a copy of smb.conf with the domain data
    # so container re-creation still finds a matching config
    cp /etc/samba/smb.conf "${STATE_DIR}/smb.conf.bak"
    touch "${STATE_DIR}/.provisioned"
    echo ">>> Provisioning complete. Users: bob, carol (Password1!)  Admin: Administrator"
else
    echo ">>> Domain already provisioned; restoring config and starting."
    cp "${STATE_DIR}/smb.conf.bak" /etc/samba/smb.conf
fi

# Run the AD DC in the foreground (interactive mode logs to stdout for `docker logs`)
exec samba -i -d 1
