# ============================================================
# AWS Application Load Balancer
# Generated by terraform_resource_generator.py
#
# IMPORTANT: Search for REPLACE_ME before terraform apply.
# ============================================================

resource "aws_lb" "app" {
  name               = "REPLACE_ME-alb"
  internal           = false
  load_balancer_type = "application"

  security_groups = [
    aws_security_group.alb.id
  ]

  # ALBs normally span at least two Availability Zones.
  subnets = [
    aws_subnet.public_a.id,
    aws_subnet.public_b.id
  ]

  enable_deletion_protection = false
  drop_invalid_header_fields = true

  tags = {
    Name        = "REPLACE_ME-alb"
    Environment = "REPLACE_ME"
    ManagedBy   = "Terraform"
  }
}
