# ============================================================
# EC2 + ALB Starter Stack
# Generated by terraform_resource_generator.py
#
# IMPORTANT: Search for REPLACE_ME before terraform apply.
# ============================================================

# ------------------------------------------------------------
# Variables / placeholders
# ------------------------------------------------------------

variable "vpc_id" {
  description = "Existing VPC ID"
  type        = string
  default     = "REPLACE_ME_VPC_ID"
}

variable "ami_id" {
  description = "AMI for the EC2 instance"
  type        = string
  default     = "REPLACE_ME_AMI_ID"
}

# ------------------------------------------------------------
# Subnets
# REPLACE_ME: update CIDRs and Availability Zones.
# ------------------------------------------------------------

resource "aws_subnet" "app_a" {
  vpc_id            = var.vpc_id
  cidr_block        = "REPLACE_ME_SUBNET_A_CIDR"
  availability_zone = "REPLACE_ME_AZ_A"

  tags = {
    Name      = "app-subnet-a"
    ManagedBy = "Terraform"
  }
}

resource "aws_subnet" "app_b" {
  vpc_id            = var.vpc_id
  cidr_block        = "REPLACE_ME_SUBNET_B_CIDR"
  availability_zone = "REPLACE_ME_AZ_B"

  tags = {
    Name      = "app-subnet-b"
    ManagedBy = "Terraform"
  }
}

# ------------------------------------------------------------
# ALB Security Group
# ------------------------------------------------------------

resource "aws_security_group" "app_alb" {
  name        = "app-alb-sg"
  description = "Security group for app ALB"
  vpc_id      = var.vpc_id

  ingress {
    description = "REPLACE_ME allowed client traffic"
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"

    # REPLACE_ME with your approved corporate/client CIDR.
    cidr_blocks = ["REPLACE_ME_CLIENT_CIDR"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name      = "app-alb-sg"
    ManagedBy = "Terraform"
  }
}

# ------------------------------------------------------------
# EC2 Security Group
# Only accepts application traffic from the ALB security group.
# ------------------------------------------------------------

resource "aws_security_group" "app_ec2" {
  name        = "app-ec2-sg"
  description = "Security group for app EC2"
  vpc_id      = var.vpc_id

  ingress {
    description     = "Application traffic from ALB"
    from_port       = 80
    to_port         = 80
    protocol        = "tcp"
    security_groups = [aws_security_group.app_alb.id]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name      = "app-ec2-sg"
    ManagedBy = "Terraform"
  }
}

# ------------------------------------------------------------
# EC2 Instance
# ------------------------------------------------------------

resource "aws_instance" "app" {
  ami                         = var.ami_id
  instance_type               = "t3.micro"
  subnet_id                   = aws_subnet.app_a.id
  vpc_security_group_ids      = [aws_security_group.app_ec2.id]
  associate_public_ip_address = false

  # REPLACE_ME with a real IAM instance profile.
  # An SSM-enabled profile is useful for private instances.
  iam_instance_profile = "REPLACE_ME_INSTANCE_PROFILE"

  metadata_options {
    http_endpoint = "enabled"
    http_tokens   = "required"
  }

  root_block_device {
    encrypted   = true
    volume_type = "gp3"
    volume_size = 8
  }

  user_data = <<-EOF
    #!/bin/bash
    set -e

    # REPLACE_ME with your real application bootstrap.
    dnf install -y nginx
    systemctl enable nginx
    systemctl start nginx
    echo "<h1>Hello from app</h1>" > /usr/share/nginx/html/index.html
  EOF

  tags = {
    Name        = "app-ec2"
    Environment = "REPLACE_ME"
    ManagedBy   = "Terraform"
  }
}

# ------------------------------------------------------------
# Application Load Balancer
# ------------------------------------------------------------

resource "aws_lb" "app" {
  name               = "app-alb"
  internal           = false
  load_balancer_type = "application"
  security_groups    = [aws_security_group.app_alb.id]

  subnets = [
    aws_subnet.app_a.id,
    aws_subnet.app_b.id
  ]

  drop_invalid_header_fields = true

  tags = {
    Name        = "app-alb"
    Environment = "REPLACE_ME"
    ManagedBy   = "Terraform"
  }
}

# ------------------------------------------------------------
# Target Group
# ------------------------------------------------------------

resource "aws_lb_target_group" "app" {
  name        = "app-tg"
  port        = 80
  protocol    = "HTTP"
  vpc_id      = var.vpc_id
  target_type = "instance"

  health_check {
    enabled             = true
    path                = "/"
    healthy_threshold   = 2
    unhealthy_threshold = 2
    interval            = 30
    timeout             = 5
    matcher             = "200-399"
  }
}

resource "aws_lb_target_group_attachment" "app" {
  target_group_arn = aws_lb_target_group.app.arn
  target_id        = aws_instance.app.id
  port             = 80
}

# ------------------------------------------------------------
# HTTP Listener
# ------------------------------------------------------------

resource "aws_lb_listener" "app_http" {
  load_balancer_arn = aws_lb.app.arn
  port              = 80
  protocol          = "HTTP"

  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.app.arn
  }
}

output "alb_dns_name" {
  value = aws_lb.app.dns_name
}

output "ec2_instance_id" {
  value = aws_instance.app.id
}
