# ============================================================
# AWS EC2 Instance
# Generated by terraform_resource_generator.py
#
# IMPORTANT: Search for REPLACE_ME before terraform apply.
# ============================================================

resource "aws_instance" "web" {
  ami                         = "REPLACE_ME_AMI_ID"
  instance_type               = "t3.micro"
  subnet_id                   = aws_subnet.private_a.id
  vpc_security_group_ids      = [aws_security_group.web.id]
  associate_public_ip_address = false
  iam_instance_profile        = "REPLACE_ME_INSTANCE_PROFILE"

  user_data = <<-EOF
    #!/bin/bash
    set -e

    # REPLACE_ME with your real application bootstrap.
    dnf install -y nginx
    systemctl enable nginx
    systemctl start nginx
    echo "<h1>Hello from Terraform EC2</h1>" > /usr/share/nginx/html/index.html
  EOF

  metadata_options {
    http_endpoint = "enabled"
    http_tokens   = "required"
  }

  root_block_device {
    encrypted   = true
    volume_type = "gp3"
    volume_size = 8
  }

  tags = {
    Name        = "REPLACE_ME-web-server"
    Environment = "REPLACE_ME"
    Application = "REPLACE_ME"
    ManagedBy   = "Terraform"
  }
}
