#!/usr/bin/env python3
"""
terraform_resource_generator.py

Interactive starter Terraform generator for AWS resources.

Examples:
    python terraform_resource_generator.py --resource ec2
    python terraform_resource_generator.py --resource alb --output alb.tf
    python terraform_resource_generator.py --resource ec2-alb-stack --output app.tf
"""

import argparse
import re
from pathlib import Path


def ask(prompt, default=None, required=False):
    """Ask the user a question with an optional default."""
    while True:
        suffix = f" [{default}]" if default is not None else ""
        value = input(f"{prompt}{suffix}: ").strip()

        if value:
            return value

        if default is not None:
            return str(default)

        if not required:
            return ""

        print("A value is required.")


def ask_yes_no(prompt, default=True):
    """Ask a yes/no question."""
    hint = "Y/n" if default else "y/N"

    while True:
        value = input(f"{prompt} [{hint}]: ").strip().lower()

        if value == "":
            return default
        if value in {"y", "yes"}:
            return True
        if value in {"n", "no"}:
            return False

        print("Please enter y or n.")


def tf_name(value):
    """Convert a friendly name into a Terraform local resource name."""
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9_]+", "_", value)
    value = re.sub(r"_+", "_", value).strip("_")

    if not value:
        return "this"
    if value[0].isdigit():
        return f"resource_{value}"
    return value


def quote(value):
    value = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{value}"'


def tf_bool(value):
    return "true" if value else "false"


def reference_or_string(value):
    """Keep Terraform references unquoted; quote literal values/placeholders."""
    ref_prefixes = ("aws_", "data.", "var.", "local.", "module.")
    return value if value.startswith(ref_prefixes) else quote(value)


def header(title):
    return f"""# ============================================================
# {title}
# Generated by terraform_resource_generator.py
#
# IMPORTANT: Search for REPLACE_ME before terraform apply.
# ============================================================

"""


def generate_vpc():
    print("\n--- VPC Resource ---")
    resource_name = tf_name(ask("Terraform resource name", "main"))
    name_tag = ask("AWS Name tag", "REPLACE_ME-vpc")
    cidr = ask("VPC CIDR block", "10.0.0.0/16")
    dns_support = ask_yes_no("Enable DNS support?", True)
    dns_hostnames = ask_yes_no("Enable DNS hostnames?", True)

    return header("AWS VPC") + f"""resource \"aws_vpc\" \"{resource_name}\" {{
  cidr_block           = {quote(cidr)}
  enable_dns_support   = {tf_bool(dns_support)}
  enable_dns_hostnames = {tf_bool(dns_hostnames)}

  tags = {{
    Name        = {quote(name_tag)}
    Environment = \"REPLACE_ME\"
    ManagedBy   = \"Terraform\"
  }}
}}
"""


def generate_subnet():
    print("\n--- Subnet Resource ---")
    resource_name = tf_name(ask("Terraform resource name", "public_a"))
    name_tag = ask("AWS Name tag", "REPLACE_ME-public-subnet-a")
    vpc_ref = ask("VPC ID or Terraform reference", "aws_vpc.main.id")
    cidr = ask("Subnet CIDR block", "10.0.1.0/24")
    az = ask("Availability Zone", "REPLACE_ME_AZ")
    public = ask_yes_no("Automatically assign public IPs?", True)
    subnet_type = "public" if public else "private"

    return header("AWS Subnet") + f"""resource \"aws_subnet\" \"{resource_name}\" {{
  vpc_id                  = {reference_or_string(vpc_ref)}
  cidr_block              = {quote(cidr)}
  availability_zone       = {quote(az)}
  map_public_ip_on_launch = {tf_bool(public)}

  tags = {{
    Name        = {quote(name_tag)}
    Environment = \"REPLACE_ME\"
    Type        = \"{subnet_type}\"
    ManagedBy   = \"Terraform\"
  }}
}}
"""


def generate_security_group():
    print("\n--- Security Group Resource ---")
    resource_name = tf_name(ask("Terraform resource name", "web"))
    sg_name = ask("AWS security group name", "REPLACE_ME-web-sg")
    description = ask("Description", "REPLACE_ME security group")
    vpc_ref = ask("VPC ID or Terraform reference", "aws_vpc.main.id")
    port = ask("Main inbound TCP port", "80")
    source = ask("Inbound source CIDR", "REPLACE_ME_CLIENT_CIDR")

    return header("AWS Security Group") + f"""resource \"aws_security_group\" \"{resource_name}\" {{
  name        = {quote(sg_name)}
  description = {quote(description)}
  vpc_id      = {reference_or_string(vpc_ref)}

  ingress {{
    description = \"REPLACE_ME inbound rule\"
    from_port   = {port}
    to_port     = {port}
    protocol    = \"tcp\"
    cidr_blocks = [{quote(source)}]
  }}

  egress {{
    description = \"Allow outbound traffic\"
    from_port   = 0
    to_port     = 0
    protocol    = \"-1\"
    cidr_blocks = [\"0.0.0.0/0\"]
  }}

  tags = {{
    Name        = {quote(sg_name)}
    Environment = \"REPLACE_ME\"
    ManagedBy   = \"Terraform\"
  }}
}}
"""


def generate_ec2():
    print("\n--- EC2 Resource ---")
    resource_name = tf_name(ask("Terraform resource name", "web"))
    instance_name = ask("EC2 Name tag", "REPLACE_ME-web-server")
    ami = ask("AMI ID or Terraform/data reference", "REPLACE_ME_AMI_ID")
    instance_type = ask("EC2 instance type", "t3.micro")
    subnet_ref = ask("Subnet ID or Terraform reference", "aws_subnet.private_a.id")
    sg_ref = ask("Security group ID/reference", "aws_security_group.web.id")
    iam_profile = ask("IAM instance profile name/reference", "REPLACE_ME_INSTANCE_PROFILE")
    key_name = ask("EC2 key pair name; blank for none", "")
    public_ip = ask_yes_no("Associate a public IP?", False)
    user_data_enabled = ask_yes_no("Add simple nginx user_data?", True)

    key_line = f"  key_name                    = {quote(key_name)}\n" if key_name else ""

    user_data = ""
    if user_data_enabled:
        user_data = """  user_data = <<-EOF
    #!/bin/bash
    set -e

    # REPLACE_ME with your real application bootstrap.
    dnf install -y nginx
    systemctl enable nginx
    systemctl start nginx
    echo \"<h1>Hello from Terraform EC2</h1>\" > /usr/share/nginx/html/index.html
  EOF

"""

    return header("AWS EC2 Instance") + f"""resource \"aws_instance\" \"{resource_name}\" {{
  ami                         = {reference_or_string(ami)}
  instance_type               = {quote(instance_type)}
  subnet_id                   = {reference_or_string(subnet_ref)}
  vpc_security_group_ids      = [{reference_or_string(sg_ref)}]
  associate_public_ip_address = {tf_bool(public_ip)}
  iam_instance_profile        = {reference_or_string(iam_profile)}
{key_line}
{user_data}  metadata_options {{
    http_endpoint = \"enabled\"
    http_tokens   = \"required\"
  }}

  root_block_device {{
    encrypted   = true
    volume_type = \"gp3\"
    volume_size = 8
  }}

  tags = {{
    Name        = {quote(instance_name)}
    Environment = \"REPLACE_ME\"
    Application = \"REPLACE_ME\"
    ManagedBy   = \"Terraform\"
  }}
}}
"""


def generate_alb():
    print("\n--- Application Load Balancer Resource ---")
    resource_name = tf_name(ask("Terraform resource name", "app"))
    alb_name = ask("AWS ALB name", "REPLACE_ME-alb")
    internal = ask_yes_no("Is this an internal/private ALB?", False)
    sg_ref = ask("Security group reference", "aws_security_group.alb.id")
    subnet_1 = ask("First subnet ID/reference", "aws_subnet.public_a.id")
    subnet_2 = ask("Second subnet ID/reference", "aws_subnet.public_b.id")
    deletion_protection = ask_yes_no("Enable deletion protection?", False)

    return header("AWS Application Load Balancer") + f"""resource \"aws_lb\" \"{resource_name}\" {{
  name               = {quote(alb_name)}
  internal           = {tf_bool(internal)}
  load_balancer_type = \"application\"

  security_groups = [
    {reference_or_string(sg_ref)}
  ]

  # ALBs normally span at least two Availability Zones.
  subnets = [
    {reference_or_string(subnet_1)},
    {reference_or_string(subnet_2)}
  ]

  enable_deletion_protection = {tf_bool(deletion_protection)}
  drop_invalid_header_fields = true

  tags = {{
    Name        = {quote(alb_name)}
    Environment = \"REPLACE_ME\"
    ManagedBy   = \"Terraform\"
  }}
}}
"""


def generate_target_group():
    print("\n--- ALB Target Group Resource ---")
    resource_name = tf_name(ask("Terraform resource name", "app"))
    target_name = ask("AWS target group name", "REPLACE_ME-tg")
    port = ask("Application port", "80")
    protocol = ask("Protocol", "HTTP").upper()
    vpc_ref = ask("VPC ID or Terraform reference", "aws_vpc.main.id")
    health_path = ask("Health check path", "/")

    return header("AWS ALB Target Group") + f"""resource \"aws_lb_target_group\" \"{resource_name}\" {{
  name        = {quote(target_name)}
  port        = {port}
  protocol    = {quote(protocol)}
  vpc_id      = {reference_or_string(vpc_ref)}
  target_type = \"instance\"

  health_check {{
    enabled             = true
    path                = {quote(health_path)}
    protocol            = {quote(protocol)}
    healthy_threshold   = 2
    unhealthy_threshold = 2
    interval            = 30
    timeout             = 5
    matcher             = \"200-399\"
  }}

  tags = {{
    Name        = {quote(target_name)}
    Environment = \"REPLACE_ME\"
    ManagedBy   = \"Terraform\"
  }}
}}
"""


def generate_listener():
    print("\n--- ALB Listener Resource ---")
    resource_name = tf_name(ask("Terraform resource name", "http"))
    alb_ref = ask("ALB ARN/reference", "aws_lb.app.arn")
    port = ask("Listener port", "80")
    protocol = ask("Listener protocol", "HTTP").upper()
    tg_ref = ask("Target group ARN/reference", "aws_lb_target_group.app.arn")

    certificate_line = ""
    if protocol == "HTTPS":
        certificate = ask("ACM certificate ARN/reference", "REPLACE_ME_CERTIFICATE_ARN")
        certificate_line = f"  certificate_arn   = {reference_or_string(certificate)}\n"

    return header("AWS ALB Listener") + f"""resource \"aws_lb_listener\" \"{resource_name}\" {{
  load_balancer_arn = {reference_or_string(alb_ref)}
  port              = {port}
  protocol          = {quote(protocol)}
{certificate_line}
  default_action {{
    type             = \"forward\"
    target_group_arn = {reference_or_string(tg_ref)}
  }}
}}
"""


def generate_ec2_alb_stack():
    print("\n--- EC2 + ALB Starter Stack ---")
    print("This writes a starter stack with obvious REPLACE_ME values.\n")

    prefix = tf_name(ask("Terraform name prefix", "app"))
    app_port = ask("Application port", "80")
    instance_type = ask("EC2 instance type", "t3.micro")
    public_alb = ask_yes_no("Should the ALB be internet-facing?", True)
    alb_internal = not public_alb

    return header("EC2 + ALB Starter Stack") + f"""# ------------------------------------------------------------
# Variables / placeholders
# ------------------------------------------------------------

variable \"vpc_id\" {{
  description = \"Existing VPC ID\"
  type        = string
  default     = \"REPLACE_ME_VPC_ID\"
}}

variable \"ami_id\" {{
  description = \"AMI for the EC2 instance\"
  type        = string
  default     = \"REPLACE_ME_AMI_ID\"
}}

# ------------------------------------------------------------
# Subnets
# REPLACE_ME: update CIDRs and Availability Zones.
# ------------------------------------------------------------

resource \"aws_subnet\" \"{prefix}_a\" {{
  vpc_id            = var.vpc_id
  cidr_block        = \"REPLACE_ME_SUBNET_A_CIDR\"
  availability_zone = \"REPLACE_ME_AZ_A\"

  tags = {{
    Name      = \"{prefix}-subnet-a\"
    ManagedBy = \"Terraform\"
  }}
}}

resource \"aws_subnet\" \"{prefix}_b\" {{
  vpc_id            = var.vpc_id
  cidr_block        = \"REPLACE_ME_SUBNET_B_CIDR\"
  availability_zone = \"REPLACE_ME_AZ_B\"

  tags = {{
    Name      = \"{prefix}-subnet-b\"
    ManagedBy = \"Terraform\"
  }}
}}

# ------------------------------------------------------------
# ALB Security Group
# ------------------------------------------------------------

resource \"aws_security_group\" \"{prefix}_alb\" {{
  name        = \"{prefix}-alb-sg\"
  description = \"Security group for {prefix} ALB\"
  vpc_id      = var.vpc_id

  ingress {{
    description = \"REPLACE_ME allowed client traffic\"
    from_port   = 80
    to_port     = 80
    protocol    = \"tcp\"

    # REPLACE_ME with your approved corporate/client CIDR.
    cidr_blocks = [\"REPLACE_ME_CLIENT_CIDR\"]
  }}

  egress {{
    from_port   = 0
    to_port     = 0
    protocol    = \"-1\"
    cidr_blocks = [\"0.0.0.0/0\"]
  }}

  tags = {{
    Name      = \"{prefix}-alb-sg\"
    ManagedBy = \"Terraform\"
  }}
}}

# ------------------------------------------------------------
# EC2 Security Group
# Only accepts application traffic from the ALB security group.
# ------------------------------------------------------------

resource \"aws_security_group\" \"{prefix}_ec2\" {{
  name        = \"{prefix}-ec2-sg\"
  description = \"Security group for {prefix} EC2\"
  vpc_id      = var.vpc_id

  ingress {{
    description     = \"Application traffic from ALB\"
    from_port       = {app_port}
    to_port         = {app_port}
    protocol        = \"tcp\"
    security_groups = [aws_security_group.{prefix}_alb.id]
  }}

  egress {{
    from_port   = 0
    to_port     = 0
    protocol    = \"-1\"
    cidr_blocks = [\"0.0.0.0/0\"]
  }}

  tags = {{
    Name      = \"{prefix}-ec2-sg\"
    ManagedBy = \"Terraform\"
  }}
}}

# ------------------------------------------------------------
# EC2 Instance
# ------------------------------------------------------------

resource \"aws_instance\" \"{prefix}\" {{
  ami                         = var.ami_id
  instance_type               = \"{instance_type}\"
  subnet_id                   = aws_subnet.{prefix}_a.id
  vpc_security_group_ids      = [aws_security_group.{prefix}_ec2.id]
  associate_public_ip_address = false

  # REPLACE_ME with a real IAM instance profile.
  # An SSM-enabled profile is useful for private instances.
  iam_instance_profile = \"REPLACE_ME_INSTANCE_PROFILE\"

  metadata_options {{
    http_endpoint = \"enabled\"
    http_tokens   = \"required\"
  }}

  root_block_device {{
    encrypted   = true
    volume_type = \"gp3\"
    volume_size = 8
  }}

  user_data = <<-EOF
    #!/bin/bash
    set -e

    # REPLACE_ME with your real application bootstrap.
    dnf install -y nginx
    systemctl enable nginx
    systemctl start nginx
    echo \"<h1>Hello from {prefix}</h1>\" > /usr/share/nginx/html/index.html
  EOF

  tags = {{
    Name        = \"{prefix}-ec2\"
    Environment = \"REPLACE_ME\"
    ManagedBy   = \"Terraform\"
  }}
}}

# ------------------------------------------------------------
# Application Load Balancer
# ------------------------------------------------------------

resource \"aws_lb\" \"{prefix}\" {{
  name               = \"{prefix}-alb\"
  internal           = {tf_bool(alb_internal)}
  load_balancer_type = \"application\"
  security_groups    = [aws_security_group.{prefix}_alb.id]

  subnets = [
    aws_subnet.{prefix}_a.id,
    aws_subnet.{prefix}_b.id
  ]

  drop_invalid_header_fields = true

  tags = {{
    Name        = \"{prefix}-alb\"
    Environment = \"REPLACE_ME\"
    ManagedBy   = \"Terraform\"
  }}
}}

# ------------------------------------------------------------
# Target Group
# ------------------------------------------------------------

resource \"aws_lb_target_group\" \"{prefix}\" {{
  name        = \"{prefix}-tg\"
  port        = {app_port}
  protocol    = \"HTTP\"
  vpc_id      = var.vpc_id
  target_type = \"instance\"

  health_check {{
    enabled             = true
    path                = \"/\"
    healthy_threshold   = 2
    unhealthy_threshold = 2
    interval            = 30
    timeout             = 5
    matcher             = \"200-399\"
  }}
}}

resource \"aws_lb_target_group_attachment\" \"{prefix}\" {{
  target_group_arn = aws_lb_target_group.{prefix}.arn
  target_id        = aws_instance.{prefix}.id
  port             = {app_port}
}}

# ------------------------------------------------------------
# HTTP Listener
# ------------------------------------------------------------

resource \"aws_lb_listener\" \"{prefix}_http\" {{
  load_balancer_arn = aws_lb.{prefix}.arn
  port              = 80
  protocol          = \"HTTP\"

  default_action {{
    type             = \"forward\"
    target_group_arn = aws_lb_target_group.{prefix}.arn
  }}
}}

output \"alb_dns_name\" {{
  value = aws_lb.{prefix}.dns_name
}}

output \"ec2_instance_id\" {{
  value = aws_instance.{prefix}.id
}}
"""


GENERATORS = {
    "vpc": generate_vpc,
    "subnet": generate_subnet,
    "security-group": generate_security_group,
    "ec2": generate_ec2,
    "alb": generate_alb,
    "target-group": generate_target_group,
    "listener": generate_listener,
    "ec2-alb-stack": generate_ec2_alb_stack,
}


def build_parser():
    parser = argparse.ArgumentParser(
        description="Interactive AWS Terraform resource generator."
    )
    parser.add_argument(
        "--resource",
        "-r",
        required=True,
        choices=sorted(GENERATORS),
        help="Resource type to generate."
    )
    parser.add_argument(
        "--output",
        "-o",
        help="Optional .tf output file. If omitted, Terraform is printed."
    )
    return parser


def main():
    args = build_parser().parse_args()
    terraform = GENERATORS[args.resource]()

    if args.output:
        output_path = Path(args.output)
        if output_path.suffix != ".tf":
            output_path = output_path.with_suffix(".tf")
        output_path.write_text(terraform, encoding="utf-8")
        print(f"\nTerraform written to: {output_path}")
        print("IMPORTANT: Search for REPLACE_ME before terraform apply.")
    else:
        print("\n" + terraform)
        print("IMPORTANT: Search for REPLACE_ME before terraform apply.")


if __name__ == "__main__":
    main()
