[app_servers]
server1 ansible_host=server1 kafka_node_id=1 kafka_external_port=19092 nifi_host_port=18443
server2 ansible_host=server2 kafka_node_id=2 kafka_external_port=29092 nifi_host_port=28443
server3 ansible_host=server3 kafka_node_id=3 kafka_external_port=39092 nifi_host_port=38443

[kafka]
server1
server2
server3

[nifi]
server1
server2
server3

[all:vars]
ansible_user=ansible
ansible_password=ansible
ansible_become=true
ansible_become_method=sudo
